# Generated by Django 2.2.14 on 2020-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='YYhgfhfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjhgj', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
